apiVersion: v1
kind: Service
metadata:
  name: flask-web
spec:
  selector:
    app: flask-web
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}

