apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  selector:
    app: haproxy
  type: {{ .Values.haproxy.service.type }}
  ports:
    - name: http
      port: {{ .Values.haproxy.service.ports.http }}
      targetPort: {{ .Values.haproxy.service.ports.http }}
      nodePort: {{ .Values.haproxy.service.nodePorts.http }}
    - name: stats
      port: {{ .Values.haproxy.service.ports.stats }}
      targetPort: {{ .Values.haproxy.service.ports.stats }}

