apiVersion: v1
kind: Service
metadata:
  name: flask-web
spec:
  selector:
    app: flask-web
  ports:
    - name: http
      port: 80             # Cổng Service expose ra trong cluster
      targetPort: 5000     # Flask container chạy cổng 5000
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}

