image:
  repository: lamluongkhe/web          # Image Flask của bạn
  tag: latest
  pullPolicy: Always

mysql:
  image: mysql:8.0
  rootPassword: root
  database: flask_login_demo
  user: kheuser
  password: "123"

service:
  type: NodePort
  port: 80
  nodePort: 30081                      # ⚠️ KHÔNG trùng với HAProxy (HAProxy đang dùng 30080)

haproxy:
  image: haproxy:3.2.4
  statsUser: admin
  statsPass: 123456

