image:
  repository: lamluongkhe/web
  tag: latest
  pullPolicy: Always

mysql:
  image: mysql:8.0
  rootPassword: root
  database: flask_login_demo
  user: kheuser
  password: 123

service:
  type: NodePort
  nodePort: 30080
  port: 80
haproxy:
  image: haproxy:3.2.4                        # Image HAProxy chính thức
  statsUser: admin                            # User truy cập trang /haproxy?stats
  statsPass: 123456    
